// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Composable, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { B3A9Db44Be281C210Db1Dc5686205879Data, B3A9Db44Be281C210Db1Dc5686205879Error, B3A9Db44Be281C210Db1Dc5686205879Response, B5A8E97C01De37E7F49653dData, B5A8E97C01De37E7F49653dError, B5A8E97C01De37E7F49653dResponse, Be28363C04C1Cd7C100107417E944C1Data, Be28363C04C1Cd7C100107417E944C1Error, Be28363C04C1Cd7C100107417E944C1Response, Bedf832894D55C9C5A4693541B0B2A5Data, Bedf832894D55C9C5A4693541B0B2A5Error, Bedf832894D55C9C5A4693541B0B2A5Response, C3893Ea1Ca41948Fc2Ab2Ef3A0209Data, C3893Ea1Ca41948Fc2Ab2Ef3A0209Error, C3893Ea1Ca41948Fc2Ab2Ef3A0209Response, D872D3E3A28C31D4C30C076F70E11D7Data, D872D3E3A28C31D4C30C076F70E11D7Error, D872D3E3A28C31D4C30C076F70E11D7Response, E55709238E32Fe7D749B26E30Data, E55709238E32Fe7D749B26E30Error, E55709238E32Fe7D749B26E30Response, Ffba1E96F748Cd3857A2B9482Cef3EbData, Ffba1E96F748Cd3857A2B9482Cef3EbError, Ffba1E96F748Cd3857A2B9482Cef3EbResponse, GetCsrfCookieData, GetCsrfCookieResponse, SignupData, SignupError, SignupResponse } from './types.gen';

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Получить CSRF токен
 *
 * Генерирует и возвращает в XSRF-TOKEN cookie новый CSRF токен
 */
export const getCsrfCookie = <TComposable extends Composable = '$fetch', DefaultT extends GetCsrfCookieResponse = GetCsrfCookieResponse>(options: Options<TComposable, GetCsrfCookieData, GetCsrfCookieResponse, DefaultT>) => {
    return (options.client ?? client).get<TComposable, GetCsrfCookieResponse | DefaultT, unknown, DefaultT>({
        url: '/sanctum/csrf-cookie',
        ...options
    });
};

/**
 * Создать новую достопримечательность
 *
 * Создаёт и возвращает новую достопримечательность в случае успеха
 */
export const b3A9Db44Be281C210Db1Dc5686205879 = <TComposable extends Composable = '$fetch', DefaultT extends B3A9Db44Be281C210Db1Dc5686205879Response = B3A9Db44Be281C210Db1Dc5686205879Response>(options: Options<TComposable, B3A9Db44Be281C210Db1Dc5686205879Data, B3A9Db44Be281C210Db1Dc5686205879Response, DefaultT>) => {
    return (options.client ?? client).post<TComposable, B3A9Db44Be281C210Db1Dc5686205879Response | DefaultT, B3A9Db44Be281C210Db1Dc5686205879Error, DefaultT>({
        ...formDataBodySerializer,
        url: '/api/poi/create',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Получить список достопримечательностей
 *
 * Возвращает список всех достопримечательностей
 */
export const e55709238E32Fe7D749B26E30 = <TComposable extends Composable = '$fetch', DefaultT extends E55709238E32Fe7D749B26E30Response = E55709238E32Fe7D749B26E30Response>(options: Options<TComposable, E55709238E32Fe7D749B26E30Data, E55709238E32Fe7D749B26E30Response, DefaultT>) => {
    return (options.client ?? client).get<TComposable, E55709238E32Fe7D749B26E30Response | DefaultT, E55709238E32Fe7D749B26E30Error, DefaultT>({
        url: '/api/poi/list',
        ...options
    });
};

/**
 * Контент по Удмуртии
 *
 * Возвращает статический контент в формате markdown для страницы
 */
export const b5A8E97C01De37E7F49653D = <TComposable extends Composable = '$fetch', DefaultT extends B5A8E97C01De37E7F49653dResponse = B5A8E97C01De37E7F49653dResponse>(options: Options<TComposable, B5A8E97C01De37E7F49653dData, B5A8E97C01De37E7F49653dResponse, DefaultT>) => {
    return (options.client ?? client).get<TComposable, B5A8E97C01De37E7F49653dResponse | DefaultT, B5A8E97C01De37E7F49653dError, DefaultT>({
        url: '/api/content/udmurtia',
        ...options
    });
};

/**
 * Загрузить картинку для точки
 *
 * Загружает картинку для точки и возвращает её путь в случае успеха
 */
export const ffba1E96F748Cd3857A2B9482Cef3Eb = <TComposable extends Composable = '$fetch', DefaultT extends Ffba1E96F748Cd3857A2B9482Cef3EbResponse = Ffba1E96F748Cd3857A2B9482Cef3EbResponse>(options: Options<TComposable, Ffba1E96F748Cd3857A2B9482Cef3EbData, Ffba1E96F748Cd3857A2B9482Cef3EbResponse, DefaultT>) => {
    return (options.client ?? client).post<TComposable, Ffba1E96F748Cd3857A2B9482Cef3EbResponse | DefaultT, Ffba1E96F748Cd3857A2B9482Cef3EbError, DefaultT>({
        ...formDataBodySerializer,
        url: '/api/trip/image',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Создать экскурсию, маршрут и точки
 *
 * Создаёт и возвращает новую экскурсию, маршрут и привязанные к нему точки. Всё в одном запросе
 */
export const d872D3E3A28C31D4C30C076F70E11D7 = <TComposable extends Composable = '$fetch', DefaultT extends D872D3E3A28C31D4C30C076F70E11D7Response = D872D3E3A28C31D4C30C076F70E11D7Response>(options: Options<TComposable, D872D3E3A28C31D4C30C076F70E11D7Data, D872D3E3A28C31D4C30C076F70E11D7Response, DefaultT>) => {
    return (options.client ?? client).post<TComposable, D872D3E3A28C31D4C30C076F70E11D7Response | DefaultT, D872D3E3A28C31D4C30C076F70E11D7Error, DefaultT>({
        url: '/api/trip/complex',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Получить все экскурсии
 *
 * Запрос для получения списка всех экскурсий вместе с точками и маршрутами (пагинация лень пока)
 */
export const be28363C04C1Cd7C100107417E944C1 = <TComposable extends Composable = '$fetch', DefaultT extends Be28363C04C1Cd7C100107417E944C1Response = Be28363C04C1Cd7C100107417E944C1Response>(options: Options<TComposable, Be28363C04C1Cd7C100107417E944C1Data, Be28363C04C1Cd7C100107417E944C1Response, DefaultT>) => {
    return (options.client ?? client).get<TComposable, Be28363C04C1Cd7C100107417E944C1Response | DefaultT, Be28363C04C1Cd7C100107417E944C1Error, DefaultT>({
        url: '/api/trip/list',
        ...options
    });
};

/**
 * Поиск по экскурсиям, точкам и маршрутам
 *
 * Запрос для поиска по всем маршрутам, точкам и экскурсиям. Ищет в полях description, name и start_location
 */
export const bedf832894D55C9C5A4693541B0B2A5 = <TComposable extends Composable = '$fetch', DefaultT extends Bedf832894D55C9C5A4693541B0B2A5Response = Bedf832894D55C9C5A4693541B0B2A5Response>(options: Options<TComposable, Bedf832894D55C9C5A4693541B0B2A5Data, Bedf832894D55C9C5A4693541B0B2A5Response, DefaultT>) => {
    return (options.client ?? client).get<TComposable, Bedf832894D55C9C5A4693541B0B2A5Response | DefaultT, Bedf832894D55C9C5A4693541B0B2A5Error, DefaultT>({
        url: '/api/trip/search',
        ...options
    });
};

/**
 * Зарегистрировать нового пользователя
 *
 * Создаёт и возвращает нового пользователя в случае успеха
 */
export const signup = <TComposable extends Composable = '$fetch', DefaultT extends SignupResponse = SignupResponse>(options: Options<TComposable, SignupData, SignupResponse, DefaultT>) => {
    return (options.client ?? client).post<TComposable, SignupResponse | DefaultT, SignupError, DefaultT>({
        url: '/api/user/signup',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Войти в аккаунт
 *
 * Проверяет credentials и создаёт новый токен в случае успеха
 */
export const c3893Ea1Ca41948Fc2Ab2Ef3A0209 = <TComposable extends Composable = '$fetch', DefaultT extends C3893Ea1Ca41948Fc2Ab2Ef3A0209Response = C3893Ea1Ca41948Fc2Ab2Ef3A0209Response>(options: Options<TComposable, C3893Ea1Ca41948Fc2Ab2Ef3A0209Data, C3893Ea1Ca41948Fc2Ab2Ef3A0209Response, DefaultT>) => {
    return (options.client ?? client).post<TComposable, C3893Ea1Ca41948Fc2Ab2Ef3A0209Response | DefaultT, C3893Ea1Ca41948Fc2Ab2Ef3A0209Error, DefaultT>({
        url: '/api/user/signin',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
