// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateComplexTripData, CreateComplexTripErrors, CreateComplexTripResponses, CreatePoiData, CreatePoiErrors, CreatePoiResponses, CreateTripData, CreateTripErrors, CreateTripResponses, EditTripData, EditTripErrors, EditTripResponses, Ffba1E96F748Cd3857A2B9482Cef3EbData, Ffba1E96F748Cd3857A2B9482Cef3EbErrors, Ffba1E96F748Cd3857A2B9482Cef3EbResponses, GetCsrfCookieData, GetCsrfCookieResponses, GetPoisData, GetPoisResponses, GetTripByIdData, GetTripByIdErrors, GetTripByIdResponses, GetTripsData, GetTripsResponses, GetUdmurtiaPageData, GetUdmurtiaPageErrors, GetUdmurtiaPageResponses, GetUserData, GetUserErrors, GetUserResponses, SearchTripsData, SearchTripsErrors, SearchTripsResponses, SigninData, SigninErrors, SigninResponses, SignupData, SignupErrors, SignupResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Получить CSRF токен
 *
 * Генерирует и возвращает в XSRF-TOKEN cookie новый CSRF токен
 */
export const getCsrfCookie = <ThrowOnError extends boolean = false>(options?: Options<GetCsrfCookieData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCsrfCookieResponses, unknown, ThrowOnError>({
        url: '/api/sanctum/csrf-cookie',
        ...options
    });
};

/**
 * Создать новую достопримечательность
 *
 * Создаёт и возвращает новую достопримечательность в случае успеха
 */
export const createPoi = <ThrowOnError extends boolean = false>(options: Options<CreatePoiData, ThrowOnError>) => {
    return (options.client ?? client).post<CreatePoiResponses, CreatePoiErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/poi/create',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Получить список достопримечательностей
 *
 * Возвращает список всех достопримечательностей
 */
export const getPois = <ThrowOnError extends boolean = false>(options?: Options<GetPoisData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPoisResponses, unknown, ThrowOnError>({
        url: '/api/poi/list',
        ...options
    });
};

/**
 * Контент по Удмуртии
 *
 * Возвращает статический контент в формате markdown для страницы
 */
export const getUdmurtiaPage = <ThrowOnError extends boolean = false>(options?: Options<GetUdmurtiaPageData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUdmurtiaPageResponses, GetUdmurtiaPageErrors, ThrowOnError>({
        url: '/api/content/udmurtia',
        ...options
    });
};

/**
 * Загрузить картинку для точки
 *
 * Загружает картинку для точки и возвращает её путь в случае успеха
 */
export const ffba1E96F748Cd3857A2B9482Cef3Eb = <ThrowOnError extends boolean = false>(options: Options<Ffba1E96F748Cd3857A2B9482Cef3EbData, ThrowOnError>) => {
    return (options.client ?? client).post<Ffba1E96F748Cd3857A2B9482Cef3EbResponses, Ffba1E96F748Cd3857A2B9482Cef3EbErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/trip/image',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Создать экскурсию
 *
 * Создаёт и возвращает новую экскурсию
 */
export const createTrip = <ThrowOnError extends boolean = false>(options?: Options<CreateTripData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateTripResponses, CreateTripErrors, ThrowOnError>({
        url: '/api/trip',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Получить экскурсию
 *
 * Запрос для получения экскурсии и её связей по ID
 */
export const getTripById = <ThrowOnError extends boolean = false>(options: Options<GetTripByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTripByIdResponses, GetTripByIdErrors, ThrowOnError>({
        url: '/api/trip/{id}',
        ...options
    });
};

/**
 * Изменить экскурсию
 *
 * Запрос для изменения экскурсии по ID
 */
export const editTrip = <ThrowOnError extends boolean = false>(options: Options<EditTripData, ThrowOnError>) => {
    return (options.client ?? client).patch<EditTripResponses, EditTripErrors, ThrowOnError>({
        url: '/api/trip/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Создать экскурсию, маршрут и точки
 *
 * Создаёт и возвращает новую экскурсию, маршрут и привязанные к нему точки. Всё в одном запросе
 */
export const createComplexTrip = <ThrowOnError extends boolean = false>(options?: Options<CreateComplexTripData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateComplexTripResponses, CreateComplexTripErrors, ThrowOnError>({
        url: '/api/trip/complex',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Получить все экскурсии
 *
 * Запрос для получения списка всех экскурсий вместе с точками и маршрутами (пагинация лень пока)
 */
export const getTrips = <ThrowOnError extends boolean = false>(options?: Options<GetTripsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTripsResponses, unknown, ThrowOnError>({
        url: '/api/trip/list',
        ...options
    });
};

/**
 * Поиск по экскурсиям, точкам и маршрутам
 *
 * Запрос для поиска по всем маршрутам, точкам и экскурсиям. Ищет в полях description, name и start_location
 */
export const searchTrips = <ThrowOnError extends boolean = false>(options?: Options<SearchTripsData, ThrowOnError>) => {
    return (options?.client ?? client).get<SearchTripsResponses, SearchTripsErrors, ThrowOnError>({
        url: '/api/trip/search',
        ...options
    });
};

/**
 * Зарегистрировать нового пользователя
 *
 * Создаёт и возвращает нового пользователя в случае успеха
 */
export const signup = <ThrowOnError extends boolean = false>(options?: Options<SignupData, ThrowOnError>) => {
    return (options?.client ?? client).post<SignupResponses, SignupErrors, ThrowOnError>({
        url: '/api/user/signup',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Войти в аккаунт
 *
 * Проверяет credentials и создаёт новый токен в случае успеха
 */
export const signin = <ThrowOnError extends boolean = false>(options?: Options<SigninData, ThrowOnError>) => {
    return (options?.client ?? client).post<SigninResponses, SigninErrors, ThrowOnError>({
        url: '/api/user/signin',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Получить пользователя по сессии
 *
 * Возвращает пользователя из сессии если это возможно
 */
export const getUser = <ThrowOnError extends boolean = false>(options?: Options<GetUserData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
        url: '/api/user/me',
        ...options
    });
};
