// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://192.168.0.131:8000' | (string & {});
};

export type GetCsrfCookieData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sanctum/csrf-cookie';
};

export type GetCsrfCookieResponses = {
    /**
     * Успешное создание
     */
    204: void;
};

export type GetCsrfCookieResponse = GetCsrfCookieResponses[keyof GetCsrfCookieResponses];

export type CreatePoiData = {
    body: {
        file: Blob | File;
        description: string;
    };
    path?: never;
    query?: never;
    url: '/api/poi/create';
};

export type CreatePoiErrors = {
    /**
     * Ошибка валидации данных
     */
    422: {
        success?: boolean;
        message?: string;
        errors?: {
            description?: Array<string>;
            file?: Array<string>;
        };
    };
};

export type CreatePoiError = CreatePoiErrors[keyof CreatePoiErrors];

export type CreatePoiResponses = {
    /**
     * Успешное создание
     */
    201: {
        success?: boolean;
        message?: string;
        data?: {
            description?: string;
            file_name?: string;
            user_id?: number;
            email?: string;
            updated_at?: string;
            created_at?: string;
            id?: number;
        };
    };
};

export type CreatePoiResponse = CreatePoiResponses[keyof CreatePoiResponses];

export type GetPoisData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/poi/list';
};

export type GetPoisResponses = {
    /**
     * Успешный вывод достопримечательностей
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<{
            description?: string;
            file_name?: string;
            user_id?: number;
            email?: string;
            updated_at?: string;
            created_at?: string;
            id?: number;
        }>;
    };
};

export type GetPoisResponse = GetPoisResponses[keyof GetPoisResponses];

export type GetUdmurtiaPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/content/udmurtia';
};

export type GetUdmurtiaPageErrors = {
    /**
     * Пользователь не авторизирован
     */
    401: {
        message?: string;
    };
};

export type GetUdmurtiaPageError = GetUdmurtiaPageErrors[keyof GetUdmurtiaPageErrors];

export type GetUdmurtiaPageResponses = {
    /**
     * Успешный вывод контента
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            name?: string;
            content?: string;
            updated_at?: string;
            created_at?: string;
            id?: number;
        };
    };
};

export type GetUdmurtiaPageResponse = GetUdmurtiaPageResponses[keyof GetUdmurtiaPageResponses];

export type Ffba1E96F748Cd3857A2B9482Cef3EbData = {
    body: {
        file: string;
    };
    path?: never;
    query?: never;
    url: '/api/trip/image';
};

export type Ffba1E96F748Cd3857A2B9482Cef3EbErrors = {
    /**
     * Пользователь не авторизирован
     */
    401: {
        message?: string;
    };
    /**
     * Роли пользователя не достаточно для выполнения операции
     */
    403: {
        success?: boolean;
        message?: string;
        errors?: Array<string>;
    };
    /**
     * Ошибка валидации данных
     */
    422: {
        success?: boolean;
        message?: string;
        errors?: {
            file?: Array<string>;
        };
    };
};

export type Ffba1E96F748Cd3857A2B9482Cef3EbError = Ffba1E96F748Cd3857A2B9482Cef3EbErrors[keyof Ffba1E96F748Cd3857A2B9482Cef3EbErrors];

export type Ffba1E96F748Cd3857A2B9482Cef3EbResponses = {
    /**
     * Успешная загрузка
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            file_name?: string;
        };
    };
};

export type Ffba1E96F748Cd3857A2B9482Cef3EbResponse = Ffba1E96F748Cd3857A2B9482Cef3EbResponses[keyof Ffba1E96F748Cd3857A2B9482Cef3EbResponses];

export type CreateTripData = {
    body?: {
        starts_at: string;
        capacity: number;
        min_age: number;
        price: number;
        route_id: number;
    };
    path?: never;
    query?: never;
    url: '/api/trip';
};

export type CreateTripErrors = {
    /**
     * Пользователь не авторизирован
     */
    401: {
        message?: string;
    };
    /**
     * Роли пользователя не достаточно для выполнения операции
     */
    403: {
        success?: boolean;
        message?: string;
        errors?: Array<string>;
    };
    /**
     * Ошибка валидации данных
     */
    422: {
        success?: boolean;
        message?: string;
        errors?: {
            starts_at?: Array<string>;
            capacity?: Array<string>;
            min_age?: Array<string>;
            price?: Array<string>;
            route_id?: Array<string>;
        };
    };
};

export type CreateTripError = CreateTripErrors[keyof CreateTripErrors];

export type CreateTripResponses = {
    /**
     * Успешное создание
     */
    201: {
        success?: boolean;
        message?: string;
        data?: {
            id: number;
            starts_at: string;
            capacity: number;
            min_age: number;
            price: number;
            route_id: number;
            created_at: string;
            updated_at: string;
        };
    };
};

export type CreateTripResponse = CreateTripResponses[keyof CreateTripResponses];

export type GetTripByIdData = {
    body?: never;
    path: {
        /**
         * ID экскурсии
         */
        id: number;
    };
    query?: never;
    url: '/api/trip/{id}';
};

export type GetTripByIdErrors = {
    /**
     * Экскурсия не найдена
     */
    404: {
        success?: boolean;
        message?: string;
    };
};

export type GetTripByIdError = GetTripByIdErrors[keyof GetTripByIdErrors];

export type GetTripByIdResponses = {
    /**
     * Экскурсия, маршрут и точки
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<{
            route?: {
                start_location?: string;
                duration?: number;
                updated_at?: string;
                created_at?: string;
                id?: number;
            };
            trip?: {
                starts_at?: string;
                capacity?: number;
                min_age?: number;
                price?: number;
                route_id?: number;
                updated_at?: string;
                created_at?: string;
                id?: number;
            };
            points?: Array<{
                file_name: string;
                description: string;
                day_of_the_route: number;
                name: string;
                updated_at?: string;
                created_at?: string;
                pivot?: {
                    route_id?: number;
                    point_id?: number;
                    day_of_the_route?: number;
                };
            }>;
        }>;
    };
};

export type GetTripByIdResponse = GetTripByIdResponses[keyof GetTripByIdResponses];

export type EditTripData = {
    body?: {
        starts_at?: string;
        capacity?: number;
        min_age?: number;
        price?: number;
        route_id?: number;
        archived?: boolean;
    };
    path: {
        /**
         * ID экскурсии
         */
        id: number;
    };
    query?: never;
    url: '/api/trip/{id}';
};

export type EditTripErrors = {
    /**
     * Пользователь не авторизирован
     */
    401: {
        message?: string;
    };
    /**
     * Роли пользователя не достаточно для выполнения операции
     */
    403: {
        success?: boolean;
        message?: string;
        errors?: Array<string>;
    };
    /**
     * Экскурсия не найдена
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Ошибка валидации данных
     */
    422: {
        success?: boolean;
        message?: string;
        errors?: {
            starts_at?: Array<string>;
            capacity?: Array<string>;
            min_age?: Array<string>;
            price?: Array<string>;
            route_id?: Array<string>;
            archived?: Array<string>;
        };
    };
};

export type EditTripError = EditTripErrors[keyof EditTripErrors];

export type EditTripResponses = {
    /**
     * Успешное обновление
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            id: number;
            starts_at: string;
            capacity: number;
            min_age: number;
            price: number;
            route_id: number;
            created_at: string;
            updated_at: string;
            archived: boolean;
        };
    };
};

export type EditTripResponse = EditTripResponses[keyof EditTripResponses];

export type CreateComplexTripData = {
    body?: {
        starts_at: string;
        capacity: number;
        min_age: number;
        price: number;
        start_location: string;
        duration: number;
        points?: Array<{
            file_name: string;
            description: string;
            day_of_the_route: number;
            name: string;
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/trip/complex';
};

export type CreateComplexTripErrors = {
    /**
     * Пользователь не авторизирован
     */
    401: {
        message?: string;
    };
    /**
     * Роли пользователя не достаточно для выполнения операции
     */
    403: {
        success?: boolean;
        message?: string;
        errors?: Array<string>;
    };
    /**
     * Ошибка валидации данных
     */
    422: {
        success?: boolean;
        message?: string;
        errors?: {
            starts_at?: Array<string>;
            capacity?: Array<string>;
            min_age?: Array<string>;
            price?: Array<string>;
            start_location?: Array<string>;
            duration?: Array<string>;
            points?: Array<string>;
            'points.n.file_name'?: Array<string>;
            'points.n.description'?: Array<string>;
            'points.n.day_of_the_route'?: Array<string>;
            'points.n.name'?: Array<string>;
        };
    };
};

export type CreateComplexTripError = CreateComplexTripErrors[keyof CreateComplexTripErrors];

export type CreateComplexTripResponses = {
    /**
     * Успешное создание
     */
    201: {
        success?: boolean;
        message?: string;
        data?: {
            route?: {
                start_location?: string;
                duration?: number;
                updated_at?: string;
                created_at?: string;
                id?: number;
            };
            trip?: {
                starts_at?: string;
                capacity?: number;
                min_age?: number;
                price?: number;
                route_id?: number;
                updated_at?: string;
                created_at?: string;
                id?: number;
            };
            points?: Array<{
                file_name: string;
                description: string;
                day_of_the_route: number;
                name: string;
                updated_at?: string;
                created_at?: string;
            }>;
        };
    };
};

export type CreateComplexTripResponse = CreateComplexTripResponses[keyof CreateComplexTripResponses];

export type GetTripsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/trip/list';
};

export type GetTripsResponses = {
    /**
     * Расширенный список эскурсий
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<{
            id: number;
            duration: number;
            price: number;
            start_location: string;
            archived: boolean;
        }>;
    };
};

export type GetTripsResponse = GetTripsResponses[keyof GetTripsResponses];

export type SearchTripsData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
    };
    url: '/api/trip/search';
};

export type SearchTripsErrors = {
    /**
     * Ошибка валидации данных
     */
    422: {
        success?: boolean;
        message?: string;
        errors?: {
            search?: Array<string>;
        };
    };
};

export type SearchTripsError = SearchTripsErrors[keyof SearchTripsErrors];

export type SearchTripsResponses = {
    /**
     * Результаты поиска
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<{
            id: number;
            duration: number;
            price: number;
            start_location: string;
            archived: boolean;
        }>;
    };
};

export type SearchTripsResponse = SearchTripsResponses[keyof SearchTripsResponses];

export type SignupData = {
    body?: {
        first_name: string;
        last_name: string;
        patronymic?: string;
        birthday: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/signup';
};

export type SignupErrors = {
    /**
     * Ошибка валидации данных
     */
    422: {
        success?: boolean;
        message?: string;
        errors?: {
            first_name?: Array<string>;
            last_name?: Array<string>;
            email?: Array<string>;
            password?: Array<string>;
            birthday?: Array<string>;
        };
    };
};

export type SignupError = SignupErrors[keyof SignupErrors];

export type SignupResponses = {
    /**
     * Успешная регистрация
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            first_name?: string;
            last_name?: string;
            patronymic?: string;
            email?: string;
            birthday?: string;
            updated_at?: string;
            created_at?: string;
            id?: number;
        };
    };
};

export type SignupResponse = SignupResponses[keyof SignupResponses];

export type SigninData = {
    body?: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/signin';
};

export type SigninErrors = {
    /**
     * Неверные credentials
     */
    401: {
        success?: boolean;
        message?: string;
        errors?: Array<string>;
    };
};

export type SigninError = SigninErrors[keyof SigninErrors];

export type SigninResponses = {
    /**
     * Успешный вход
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<string>;
    };
};

export type SigninResponse = SigninResponses[keyof SigninResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/me';
};

export type GetUserErrors = {
    /**
     * Пользователь не авторизирован
     */
    401: {
        message?: string;
    };
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Успешный вывод пользователя
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            first_name: string;
            last_name: string;
            patronymic?: string;
            birthday: string;
            email: string;
            role: string;
        };
    };
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];
