// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { createComplexTrip, createPoi, createTrip, editTrip, ffba1E96F748Cd3857A2B9482Cef3Eb, getCsrfCookie, getPois, getTripById, getTrips, getUdmurtiaPage, getUser, type Options, searchTrips, signin, signup } from '../sdk.gen';
import type { CreateComplexTripData, CreateComplexTripError, CreateComplexTripResponse, CreatePoiData, CreatePoiError, CreatePoiResponse, CreateTripData, CreateTripError, CreateTripResponse, EditTripData, EditTripError, EditTripResponse, Ffba1E96F748Cd3857A2B9482Cef3EbData, Ffba1E96F748Cd3857A2B9482Cef3EbError, Ffba1E96F748Cd3857A2B9482Cef3EbResponse, GetCsrfCookieData, GetPoisData, GetTripByIdData, GetTripsData, GetUdmurtiaPageData, GetUserData, SearchTripsData, SigninData, SigninError, SigninResponse, SignupData, SignupError, SignupResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [
        params
    ];
};

export const getCsrfCookieQueryKey = (options?: Options<GetCsrfCookieData>) => createQueryKey('getCsrfCookie', options);

/**
 * Получить CSRF токен
 *
 * Генерирует и возвращает в XSRF-TOKEN cookie новый CSRF токен
 */
export const getCsrfCookieQuery = defineQueryOptions((options?: Options<GetCsrfCookieData>) => ({
    key: getCsrfCookieQueryKey(options),
    query: async (context) => {
        const { data } = await getCsrfCookie({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Создать новую достопримечательность
 *
 * Создаёт и возвращает новую достопримечательность в случае успеха
 */
export const createPoiMutation = (options?: Partial<Options<CreatePoiData>>): UseMutationOptions<CreatePoiResponse, Options<CreatePoiData>, CreatePoiError> => {
    return {
        mutation: async (fnOptions) => {
            const { data } = await createPoi({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
};

export const getPoisQueryKey = (options?: Options<GetPoisData>) => createQueryKey('getPois', options);

/**
 * Получить список достопримечательностей
 *
 * Возвращает список всех достопримечательностей
 */
export const getPoisQuery = defineQueryOptions((options?: Options<GetPoisData>) => ({
    key: getPoisQueryKey(options),
    query: async (context) => {
        const { data } = await getPois({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getUdmurtiaPageQueryKey = (options?: Options<GetUdmurtiaPageData>) => createQueryKey('getUdmurtiaPage', options);

/**
 * Контент по Удмуртии
 *
 * Возвращает статический контент в формате markdown для страницы
 */
export const getUdmurtiaPageQuery = defineQueryOptions((options?: Options<GetUdmurtiaPageData>) => ({
    key: getUdmurtiaPageQueryKey(options),
    query: async (context) => {
        const { data } = await getUdmurtiaPage({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Загрузить картинку для точки
 *
 * Загружает картинку для точки и возвращает её путь в случае успеха
 */
export const ffba1E96F748Cd3857A2B9482Cef3EbMutation = (options?: Partial<Options<Ffba1E96F748Cd3857A2B9482Cef3EbData>>): UseMutationOptions<Ffba1E96F748Cd3857A2B9482Cef3EbResponse, Options<Ffba1E96F748Cd3857A2B9482Cef3EbData>, Ffba1E96F748Cd3857A2B9482Cef3EbError> => {
    return {
        mutation: async (fnOptions) => {
            const { data } = await ffba1E96F748Cd3857A2B9482Cef3Eb({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
};

/**
 * Создать экскурсию
 *
 * Создаёт и возвращает новую экскурсию
 */
export const createTripMutation = (options?: Partial<Options<CreateTripData>>): UseMutationOptions<CreateTripResponse, Options<CreateTripData>, CreateTripError> => {
    return {
        mutation: async (fnOptions) => {
            const { data } = await createTrip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
};

export const getTripByIdQueryKey = (options: Options<GetTripByIdData>) => createQueryKey('getTripById', options);

/**
 * Получить экскурсию
 *
 * Запрос для получения экскурсии и её связей по ID
 */
export const getTripByIdQuery = defineQueryOptions((options: Options<GetTripByIdData>) => ({
    key: getTripByIdQueryKey(options),
    query: async (context) => {
        const { data } = await getTripById({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Изменить экскурсию
 *
 * Запрос для изменения экскурсии по ID
 */
export const editTripMutation = (options?: Partial<Options<EditTripData>>): UseMutationOptions<EditTripResponse, Options<EditTripData>, EditTripError> => {
    return {
        mutation: async (fnOptions) => {
            const { data } = await editTrip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
};

/**
 * Создать экскурсию, маршрут и точки
 *
 * Создаёт и возвращает новую экскурсию, маршрут и привязанные к нему точки. Всё в одном запросе
 */
export const createComplexTripMutation = (options?: Partial<Options<CreateComplexTripData>>): UseMutationOptions<CreateComplexTripResponse, Options<CreateComplexTripData>, CreateComplexTripError> => {
    return {
        mutation: async (fnOptions) => {
            const { data } = await createComplexTrip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
};

export const getTripsQueryKey = (options?: Options<GetTripsData>) => createQueryKey('getTrips', options);

/**
 * Получить все экскурсии
 *
 * Запрос для получения списка всех экскурсий вместе с точками и маршрутами (пагинация лень пока)
 */
export const getTripsQuery = defineQueryOptions((options?: Options<GetTripsData>) => ({
    key: getTripsQueryKey(options),
    query: async (context) => {
        const { data } = await getTrips({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const searchTripsQueryKey = (options?: Options<SearchTripsData>) => createQueryKey('searchTrips', options);

/**
 * Поиск по экскурсиям, точкам и маршрутам
 *
 * Запрос для поиска по всем маршрутам, точкам и экскурсиям. Ищет в полях description, name и start_location
 */
export const searchTripsQuery = defineQueryOptions((options?: Options<SearchTripsData>) => ({
    key: searchTripsQueryKey(options),
    query: async (context) => {
        const { data } = await searchTrips({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Зарегистрировать нового пользователя
 *
 * Создаёт и возвращает нового пользователя в случае успеха
 */
export const signupMutation = (options?: Partial<Options<SignupData>>): UseMutationOptions<SignupResponse, Options<SignupData>, SignupError> => {
    return {
        mutation: async (fnOptions) => {
            const { data } = await signup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
};

/**
 * Войти в аккаунт
 *
 * Проверяет credentials и создаёт новый токен в случае успеха
 */
export const signinMutation = (options?: Partial<Options<SigninData>>): UseMutationOptions<SigninResponse, Options<SigninData>, SigninError> => {
    return {
        mutation: async (fnOptions) => {
            const { data } = await signin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
};

export const getUserQueryKey = (options?: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * Получить пользователя по сессии
 *
 * Возвращает пользователя из сессии если это возможно
 */
export const getUserQuery = defineQueryOptions((options?: Options<GetUserData>) => ({
    key: getUserQueryKey(options),
    query: async (context) => {
        const { data } = await getUser({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));
